### ISSUE TITLE
Access Blocked!

### ISSUE THREAD

**Issue by Elyuui** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#209]
![2E8ECDD6-44D8-4731-8AD2-494F0021BD00](https://user-images.githubusercontent.com/61014053/109609095-28029480-7b2b-11eb-9dad-3eff2e9f0e7e.png)

why???

**Comment by vineetchoudhary** [comment]
Hi, I'm working on it. There is some payment issue with firebase. So, AppBox installation web app was not able to process the Google reCaptcha request.

<img width="1502" alt="Screenshot 2021-03-02 at 1 23 24 PM" src="https://user-images.githubusercontent.com/8479436/109616439-24870180-7b5b-11eb-88d4-be125eba742d.png">

**Comment by vineetchoudhary** [comment]
Now all the pending payments are clear with Firebase and AppBox Web App is working fine.

**Comment by longleeproduction** [comment]
@vineetchoudhary can't install app.
Installation in progress .... and no installation popup

**Comment by gb160** [comment]
@vineetchoudhary 
Hi, when I tap 'install application' I get no iOS popup also.

**Comment by Elyuui** [comment]
> Now all the pending payments are clear with Firebase and AppBox Web App is working fine.

Thanks, now I don’t have this problem but there is no popup after “install”. I delete every app similar to the one that I want to download but nothing happens, still no popup for installation

**Comment by vineetchoudhary** [comment]
Hi All, Install application popup is fixed. Check this comment for more details - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/217#issuecomment-788781258

**Comment by vineetchoudhary** [comment]
If you are still facing this issue, please feel free to reopen.

**Comment by Elyuui** [comment]
Hi, I’m sorry but I need to reopen it. Now the installation doesn’t work ... it’s like if my udid isn’t in the certificate but there is. I already checked and update again the links but the problem persists.

**Comment by vineetchoudhary** [comment]
Hi @Elyuui, We are discussing the same issue here -  https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/217
